package: for_sa11y
version: '2.0.3'
vendor: '3.0.3'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/addon_key
requires:
    redaxo: '^5.12.0'
    php:
        version: '>=7.4, <9'
