package: for_sa11y
version: '3.0.0-dev'
vendors: 'sa11y 3.0.7'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/addon_key
requires:
    redaxo: '^5.16.0-beta1'
    php:
        version: '>=8.1, <9'
